### ISSUE TITLE
KeyError: 'os'

### ISSUE THREAD

**Issue by afagund** [pyToshka/wazuh-prometheus-exporter#12]
Whenever I have a last_registered_agent with a status never_connected, we get the error below when running the exporter. Probably due the fact that a never_connected agent does not have yet the OS info populated. Please can you check?
 
`KeyError: 'os'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/wsgiref/handlers.py", line 137, in run
    self.result = application(self.environ, self.start_response)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 128, in prometheus_app
    status, headers, output = _bake_output(registry, accept_header, accept_encoding_header, params, disable_compression)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/exposition.py", line 104, in _bake_output
    output = encoder(registry)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/openmetrics/exposition.py", line 21, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "./main.py", line 123, in collect
    for key, value in version["os"].items():
KeyError: 'os'`

**Comment by pyToshka** [comment]
@afagund thank you for raising issue, I will back soon

**Comment by pyToshka** [comment]
fixed

**Comment by afagund** [comment]
We will deploy the new tag. Thanks!
