### ISSUE TITLE
Error "KeyError: 'queued_msgs'" while getting metrics from Wazuh Manager 4.7.2

### ISSUE THREAD

**Issue by dj-wasabi** [pyToshka/wazuh-prometheus-exporter#22]
Hi. Currently running Wazuh 4.7.2, with the 'latest' docker image for the exporter as of now (2024-01-28) and when I want to start the exporter, I  get the following error:

```
{"written_at": "2024-01-28T10:53:06.548Z", "written_ts": 1706439186548555000, "msg": "Starting Wazuh prometheus exporter", "type": "log", "logger": "wazuh-exporter", "thread": "MainThread", "level": "info", "module": "main", "line_no": 551}
{"written_at": "2024-01-28T10:53:06.549Z", "written_ts": 1706439186549734000, "msg": "Start collector", "type": "log", "logger": "wazuh-exporter", "thread": "MainThread", "level": "info", "module": "main", "line_no": 62}
{"written_at": "2024-01-28T10:53:07.595Z", "written_ts": 1706439187595591000, "msg": "Got response http code 400, response body Stats file does not exist: /var/ossec/stats/totals/2024/Jan/ossec-totals-28.log", "type": "log", "logger": "root", "thread": "MainThread", "level": "warning", "module": "__init__", "line_no": 127}
Traceback (most recent call last):
  File "./main.py", line 553, in <module>
    REGISTRY.register(WazuhCollector())
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
  File "/usr/local/lib/python3.8/site-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "./main.py", line 251, in collect
    value=remote_state["queued_msgs"],
KeyError: 'queued_msgs'
```

When I do a `curl -kH 'Authorization: Bearer <SNIP>' https://10.10.1.21:55000/manager/stats?pretty=true`, I get the following response:

```json
{
   "data": {
      "affected_items": [
         {
            "hour": 10,
            "alerts": [
               {
                  "sigid": 5104,
                  "level": 8,
                  "times": 1
               },
               {
                  "sigid": 5403,
                  "level": 4,
                  "times": 1
               },
               {
                  "sigid": 5402,
                  "level": 3,
                  "times": 50
               },
               {
                  "sigid": 2930,
                  "level": 0,
                  "times": 2
               },
               {
                  "sigid": 2932,
                  "level": 7,
                  "times": 6
               },
               {
                  "sigid": 5501,
                  "level": 3,
                  "times": 57
               },
               {
                  "sigid": 5502,
                  "level": 3,
                  "times": 60
               },
               {
                  "sigid": 5721,
                  "level": 0,
                  "times": 6
               },
               {
                  "sigid": 5715,
                  "level": 3,
                  "times": 3
               },
               {
                  "sigid": 40700,
                  "level": 0,
                  "times": 120
               },
               {
                  "sigid": 80700,
                  "level": 0,
                  "times": 2121
               },
               {
                  "sigid": 80710,
                  "level": 10,
                  "times": 2
               },
               {
                  "sigid": 86003,
                  "level": 3,
                  "times": 2
               },
               {
                  "sigid": 86001,
                  "level": 1,
                  "times": 92
               },
               {
                  "sigid": 86002,
                  "level": 1,
                  "times": 3
               },
               {
                  "sigid": 5901,
                  "level": 8,
                  "times": 3
               },
               {
                  "sigid": 5902,
                  "level": 8,
                  "times": 1
               },
               {
                  "sigid": 1002,
                  "level": 2,
                  "times": 41
               },
               {
                  "sigid": 530,
                  "level": 0,
                  "times": 178
               },
               {
                  "sigid": 533,
                  "level": 7,
                  "times": 3
               },
               {
                  "sigid": 535,
                  "level": 1,
                  "times": 11
               },
               {
                  "sigid": 501,
                  "level": 3,
                  "times": 3
               },
               {
                  "sigid": 502,
                  "level": 3,
                  "times": 1
               },
               {
                  "sigid": 503,
                  "level": 3,
                  "times": 3
               },
               {
                  "sigid": 506,
                  "level": 3,
                  "times": 3
               },
               {
                  "sigid": 515,
                  "level": 0,
                  "times": 11
               },
               {
                  "sigid": 19000,
                  "level": 0,
                  "times": 746
               },
               {
                  "sigid": 19007,
                  "level": 7,
                  "times": 324
               },
               {
                  "sigid": 19011,
                  "level": 9,
                  "times": 1
               },
               {
                  "sigid": 19008,
                  "level": 3,
                  "times": 219
               },
               {
                  "sigid": 19009,
                  "level": 3,
                  "times": 6
               },
               {
                  "sigid": 19004,
                  "level": 7,
                  "times": 7
               }
            ],
            "totalAlerts": 4087,
            "events": 20890,
            "syscheck": 11,
            "firewall": 0
         }
      ],
      "total_affected_items": 1,
      "total_failed_items": 0,
      "failed_items": []
   },
   "message": "Statistical information for each node was successfully read",
   "error": 0
}
```
It is indeed missing, but so are other keys. So not sure yet if this is a me issue or a exporter issue.
If you need any additional information, don't hesitate to reach out.

**Comment by pyToshka** [comment]
@dj-wasabi hi, let me check and back

**Comment by pyToshka** [comment]
fixed. should work

**Comment by dj-wasabi** [comment]
Thanks @pyToshka 

(Nice PR though!) 👍
